telegram_bot_token: "7811702895:AAFOpxQUXUbkWrx6ksdXEM_LRRaSjnKur8M"

rag_config:
  # Пути к файлам и директориям
  docs_path: "docs"
  faiss_path: "faiss_index"
  
  # Настройки чанкинга
  semantic_chunking:
    threshold: 0.6
    max_chunk_size: 1000
    chunk_overlap: 200
  
  # Настройки GLiNER
  gliner:
    model: "urchade/gliner_small-v2.1"
    entity_extraction_threshold: 0.5
    custom_terms:
      - "замороженный хлеб"
      - "багет"
      - "конвекция"
      - "пергаментная бумага"
  
  # Настройки LLM
  llm:
    model: "qwen2.5vl:7b"
    num_ctx: 4096
    temperature: 0.3
    top_k: 50
    top_p: 0.9
  
  # Настройки ретриверов
  retrievers:
    faiss:
      k: 10
    bm25:
      k: 10
    reranker:
      model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      top_k: 5
      score_threshold: 0.3
    fusion:
      k: 10
      rrf_k: 60
      weights:
        faiss: 1.0
        bm25: 0.8
        graph: 0.5
  
  # Настройки эмбеддингов
  embeddings:
    model: "Qwen/Qwen3-Embedding-0.6B"
    batch_size: 64
    normalize: true

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "neo4jneo4j"

bot_config:
  response_timeout: 600
  max_query_length: 500
  request_cooldown: 2
  jokes:
    - "😅 Кажется, мои документы спрятались лучше, чем я в прятки! Попробуй другой вопрос!"
    - "🤓 Хм, мои нейроны немного запутались. Давай попробуем ещё раз с новым вопросом?"
    - "😜 Ой, похоже, этот вопрос слишком хитрый даже для КИРЫ! Задай что-нибудь попроще?"
    - "😂 Моя база знаний сделала перерыв на кофе. Новый вопрос, и я снова в деле!"
    - "🙈 Упс, документы ушли в отпуск! Может, спросишь что-нибудь другое?"